### ISSUE TITLE
About Rainbond 5.X RoadMap Community needs collection

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#106]
####  About community ecological docking

1. Support community Kubernetes(1.9+), Docker(1.12.x+) version. The default version is upgraded to docker(17.04.x) kubernetes(1.10.3).

   - [ ] Move the support for application storage customized in Kubernetes to the Rainbond application runtime using the CRI protocol.

   - [ ] Move the support for the Midonet multi-tenant SDN network in Kubernetes entirely through the CNI protocol to the Rainbond application runtime.

   - [ ] Use the Kubernetes native implementation for scheduling attributes on local storage support.

   - [ ] Relevant customizations on application scheduling are implemented through multiple scheduler docking.

   - [ ] PR BUG fixes about Kubernetes to the community.

   - [x] Move customizations about Docker's log processing drivers to the Rainbond application runtime.

2. The ServiceMesh architecture supports integration Istio

   - [ ] Support istio-proxy as a network governance plugin.

   - [ ] The application runtime supports Istio service discovery.

   - [ ] The console visually configures service governance.

3. Support the construction of Rainbond applications based on helm

   - [ ] Support building applications from Charts source.

   - [ ] Supports the creation of applications for the Charts definition from the Charts Repository.

####  About new feature

1. Supports Windows Container.
2. Support task (Job) plugin types for one-time tasks such as backup, data processing, etc.
3. The installation and operation (delivery) of the group application supports process control, and extensions support the execution of task plugins.
4. Application system log (stdout,stderr output) processing: added advanced query and search functions.

#### About architecture and feature optimization

1. The BuildingPack is fully upgraded

   - [ ] Support `Java` `PHP` `Python` `NodeJS` `Golang` `.NetCore`  language runtime version.

   - [ ] Support for source code builds in offline environments (with dependent package download sources)

2. Switch to etcd for datacenter data storage.

3. The stateless application run switches to the Deployment model to achieve a rolling upgrade of stateful services.

4. Change the plugin state policy to distinguish whether the processing state affects the application state.

5. MQ upgrades support operational asynchronous event lifecycle management, with event tracking implemented with eventlog.

6. The implementation of 4-layer mesh plugin is replaced with `envoy` by default, and the cluster service is optimized to find the architectural pressure.

#### 社区生态对接方面

1. 支持社区Kubernetes(1.9+)、Docker版本。默认版本升级到docker( 17.04.x ) kubernetes(1.10.3).

   - [ ] 将关于Kubernetes中定制的关于应用存储的支持使用CRI协议移至Rainbond应用运行时。

   - [ ] 将关于Kubernetes中对Midonet多租户SDN网络的的支持完全通过CNI协议移至Rainbond应用运行时。

   - [ ] 将关于本地存储支持的调度属性使用Kubernetes原生实现。

   - [ ] 将关于应用调度的相关定制通过实现多种调度器对接。

   - [ ] 将关于Kubernetes的BUG修复提交社区。

   - [ ] 将关于Docker的日志处理驱动的定制移动到Rainbond应用运行时。

2. ServiceMesh 架构支持集成Istio

   - [ ] 支持Istio-proxy作为网络治理插件。

   - [ ] 应用运行时支持Istio服务发现。

   - [ ] 控制台可视化配置服务治理。

3. 支持基于helm构建Rainbond应用

   - [ ] 支持从Charts源码构建应用。

   - [ ] 支持从Charts仓库获取Charts定义创建应用。

#### Rainbond新特性

1. 支持Windows Container。
2. 支持任务式（Job）插件类型，适用于备份，数据处理等一次性任务。
3. 组应用的安装和操作（交付）支持流程控制，扩展支持任务插件的执行。
4. 应用系统日志（stdout,stderr输出）处理：增加高级查询和搜索功能。

#### Rainbond架构与特性优化

1. BuildingPack全面升级，有条件支持离线源码构建，可以配置私有仓库服务。
2. 数据中心数据存储切换到etcd。
3. 无状态应用运行切换到Deployment模型，实现有状态服务的滚动升级。
4. 更改插件运行状态策略，区分处理插件状态是否影响应用的状态。
5. MQ升级支持操作异步事件生命周期管理，配合eventlog实现事件执行追踪。
6. 默认4层mesh插件实现更换为envoy，优化集群服务发现架构压力。

**Comment by recotone** [comment]
期待中...

**Comment by timandy** [comment]
呱唧呱唧

**Comment by lpcjuzipi** [comment]
在应用端口设置方面，修改端口目前只能是选择，可以添加手动创建端口的功能吗

**Comment by lpcjuzipi** [comment]
请问，3.7.2版本在安装过程中，salt测试过程中总是退出，在log日志中，是请求超时问题，我讲防火墙都关闭且删除规则后依然报错，请问该如何解决
