### ISSUE TITLE
V5.X RoadMap

### ISSUE THREAD

**Issue by yangkaa** [goodrain/rainbond#1298]
## V5.8.1 

- [x] Rainbond 英文化
    - [x] 产品英文化
    - [x] 文档英文化

- [x] 支持导出非容器包在服务器上直接运行

> 在一些非容器的基础环境下，如虚拟机上，我们也希望能快速部署 Rainbond 构建好的产物，此时我们需要支持导出非容器镜像的包，能直接在服务器上运行

- [x] Rainbond 默认登陆页面优化

- [x] Rainbond 默认应用治理模式调整为原生 K8s 模式

## V5.8.X

- [x] 支持 Helm 应用安装后可编排

> helm已经成为用户应用打包的规范，但是当前 Rainbond 安装的 Helm 仅仅只能配置 values 文件，我们希望 Helm 部署的应用可以像 Rainbond 内置组件一样编排。并且可以支持 Rainbond 内的应用生成 chart 包

- [x] 支持 Containerd

> 在 Kubernetes 1.24 版本以后，彻底弃用 docker，因此需要 Containerd 支持

- [x] 支持全局的 Cloud Shell

> 在需要操作集群时，可以直接通过页面访问到集群内，执行 kubectl 命令或 grctl 命令。

## V5.9.X

- [ ] 支持 pipeline 流水线功能

> 当前，Rainbond 虽然支持通过接口调用进行持续的构建、部署、和交付。但是在 ToC 场景下，一个业务的上线可能还需要人工审核或依赖于其他业务的上线。在这种情况下，通过 OpenAPI 接口调用完成持续交付会略有不足。因此我们需要支持流水线实现全自动化的部署和交付。

- [ ] 集群应用健康检查及建议

> 在集群出现问题或应用运行异常时，用户往往不知道如何排查问题。因此我们希望在应用运行异常、 Crashloopbackoff 等情况下，能在产品上给出用户指导和建议。
