### ISSUE TITLE
V5.2-beta1 roadmap

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#586]
- [x] 组件使用各类存储类型生命周期控制（存储创建、存储挂载、存储回收）
- [x]  组件查询存储支持状态展示，容量展示
- [x] 应用分享和安装存储支持类型判断选择
- [x] 应用备份支持扩展存储的元数据备份
- [ ] ETCD优化
    - [x] 全部组件支持ETCD SSL验证。#567 
    - [x] 全部组件存储数据切换到V3 Client
    - [ ] 缓存到ETCD中的数据自动清理 #568 
    - [x] 默认安装支持对接已存在etcd集群
- [x] Rainbond部署重构为Operator模式，并提供安装控制UI。
- [x] 支持通过helm安装Rainbond
- [x] 默认安装支持Kubernetes 1.16版本
- [x] 源码构建任务从管理节点容器化执行更改为kubernetes集群job任务
- [x] 源码构建支持图形化设置参数（NodeJS，NodeJSStatic）goodrain/rainbond-ui#272
- [x] 自定义Kubernetes Endpoints支持健康检测 #580
- [x] 允许组件使用privileged模式运行 #333

**Comment by welcome112s** [comment]
@barnettZQG　牛

**Comment by barnettZQG** [comment]
- [x] Go源码构建更新：增加对Go mod模式依赖包管理的支持，支持Go 1.12 1.13 #613 
- [x] Java源码构建更新，支持JDK 11 12 13 Maven 3.5.4 3.6.2
- [x] PHP源码构建更新，支持php 7.2.26 7.3.13 版本

**Comment by barnettZQG** [comment]
- [x] 应用网关支持动态更新TCP/UDP类server的upstream列表，支持轮询负载均衡算法
- [x] 应用网关支持默认设置proxy_header参数 #591

**Comment by barnettZQG** [comment]
已发布：https://github.com/goodrain/rainbond/releases/tag/v5.2.0-beta1
