### ISSUE TITLE
Rainbond 5.3 Roadmap

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#851]
- [x] Support Component Custom Monitor and Add custom dashboard support in the application scope. #370 #809  #824
- [x] Remove rbd-repo system-component. #803
  - [x] Support manage the maven setting.
  - [x] New rbd-resource-proxy system-component for Implement the build resource broker download.
- [x] Support for Kubernetes native service communication mode #830 #824
- [x] Add application scope in region #829
- [x] Add application config group support. #735
- [ ] Support migration application from Kubernetes clusters to Rainbond (experimental). #616
- [ ] Support export OAM spec application(experimental). #616

**Comment by barnettZQG** [comment]
- [ ] 支持基于Cookie 的会话保持负载均衡算法

**Comment by barnettZQG** [comment]
5.3.0 版本已发布
