### ISSUE TITLE
V5.3.1 Roadmap

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#921]
- [ ] Support for installation and independent management of applications from the Helm registry.
   - [ ] support add and edit helm registry.
   - [ ] support list applications from helm registry.
   - [ ] support install the application from helm registry.
   - [ ] support for identifying `services` generated by installed applications
   - [ ] support add and edit ingress rule to access applications.
   - [ ] support uninstall and delete the application.

**Comment by barnettZQG** [comment]
- [x] support the grpc protocol Internal governance(Load balancing, health check, intelligent routing, etc)

**Comment by barnettZQG** [comment]
#934
#931 
#927
